name: Build and Push image

on:
  schedule:
    - cron: '00 17 * * *' # 17:00 UTC
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

env:
  CONTAINER_NAME: ${{ secrets.DOCKER_USERNAME }}/base

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ env.CONTAINER_NAME }}:latest
      -
        name: Check manifest
        if: github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          docker buildx imagetools inspect ${{ env.CONTAINER_NAME }}:latest
      -
        name: Inspect image
        if: github.event_name != 'pull_request' && (endsWith(github.ref, github.event.repository.default_branch) || startsWith(github.ref, 'refs/tags/'))
        run: |
          docker pull ${{ env.CONTAINER_NAME }}:latest
          docker image inspect ${{ env.CONTAINER_NAME }}:latest
